package com.nereid.diagnostics

import java.net.URLEncoder
import java.nio.charset.StandardCharsets

object GitHubIssueBuilder {
    private const val GITHUB_REPO = "mirkozagami/nereid"
    private const val MAX_URL_LENGTH = 8000

    fun buildReportBody(
        sections: List<DiagnosticSection>,
        userComments: String?
    ): String = buildString {
        appendLine("## Bug Report")
        appendLine()
        appendLine("### Description")
        appendLine(userComments ?: "_Please describe what happened..._")
        appendLine()

        sections.forEach { section ->
            appendLine("### ${section.title}")
            appendLine(section.content)
            appendLine()
        }

        appendLine("---")
        append("*Generated by Nereid Diagnostic Reporter*")
    }

    fun buildGitHubUrl(
        sections: List<DiagnosticSection>,
        userComments: String?,
        title: String = "Bug Report"
    ): String {
        var body = buildReportBody(sections, userComments)

        // Build initial URL to check length
        var url = buildUrlWithBody(title, body)

        // Truncate if needed
        if (url.length > MAX_URL_LENGTH) {
            val truncatedSections = truncateSections(sections)
            body = buildReportBody(truncatedSections, userComments)
            body += "\n\n_Note: Report truncated due to size. Use 'Copy to Clipboard' for full details._"
            url = buildUrlWithBody(title, body)
        }

        return url
    }

    private fun buildUrlWithBody(title: String, body: String): String {
        val encodedTitle = URLEncoder.encode(title, StandardCharsets.UTF_8.toString())
        val encodedBody = URLEncoder.encode(body, StandardCharsets.UTF_8.toString())
        return "https://github.com/$GITHUB_REPO/issues/new?title=$encodedTitle&body=$encodedBody"
    }

    private fun truncateSections(sections: List<DiagnosticSection>): List<DiagnosticSection> {
        return sections.map { section ->
            val maxContentLength = 500
            if (section.content.length > maxContentLength) {
                DiagnosticSection(
                    title = section.title,
                    content = section.content.take(maxContentLength) + "\n... (truncated)"
                )
            } else {
                section
            }
        }
    }
}
