package com.nereid.diagnostics

import org.junit.Assert.*
import org.junit.Test

class GitHubIssueBuilderTest {

    @Test
    fun testBuildReportBody() {
        val sections = listOf(
            DiagnosticSection("Environment", "- IDE: Test IDE 1.0"),
            DiagnosticSection("Error Details", "Something went wrong")
        )

        val body = GitHubIssueBuilder.buildReportBody(
            sections = sections,
            userComments = "I was editing a flowchart"
        )

        assertTrue(body.contains("## Bug Report"))
        assertTrue(body.contains("### Description"))
        assertTrue(body.contains("I was editing a flowchart"))
        assertTrue(body.contains("### Environment"))
        assertTrue(body.contains("Test IDE 1.0"))
        assertTrue(body.contains("Generated by Nereid Diagnostic Reporter"))
    }

    @Test
    fun testBuildGitHubUrl() {
        val sections = listOf(
            DiagnosticSection("Environment", "- IDE: Test")
        )

        val url = GitHubIssueBuilder.buildGitHubUrl(
            sections = sections,
            userComments = "Test comment"
        )

        assertTrue(url.startsWith("https://github.com/mirkozagami/nereid/issues/new"))
        assertTrue(url.contains("title="))
        assertTrue(url.contains("body="))
    }

    @Test
    fun testTruncateLongBody() {
        val longContent = "x".repeat(10000)
        val sections = listOf(
            DiagnosticSection("Test", longContent)
        )

        val result = GitHubIssueBuilder.buildGitHubUrl(
            sections = sections,
            userComments = null
        )

        // URL should be under the limit
        assertTrue(result.length < 8200)
    }
}
